# This file stores secrets for local Streamlit development.
# It should NOT be committed to version control.
# Make sure ".streamlit/secrets.toml" is in your .gitignore file.

# IMPORTANT: Replace the placeholder below with your actual Gemini API key.
GEMINI_API_KEY = "your_new_api_key_goes_here"